services:
  uptime-kuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:1
    volumes:
      - data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

volumes:
  data: